---
abstract: "provides C<baptise>, a drop-in replacement for C<bless>; like if C<bless> created accessors for you. This module also provides additional methods built using C<h2o> or C<o2h> from Util::H2O that allow for the incremental addition of OOP into existing or small scale Perl code without having to fully commit to a Perl OOP framework or compromise one's personal Perl style."
author:
  - 'oodler577 <oodler@cpan.org>'
build_requires:
  Config::Tiny: '2.28'
  File::Temp: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.029, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Util-H2O-More
requires:
  Config::Tiny: '2.28'
  Util::H2O: '0.22'
  perl: '5.010'
resources:
  homepage: https://github.com/oodler577/p5-Util-H2O-More
  repository: https://github.com/oodler577/p5-Util-H2O-More.git
version: 0.2.9
x_generated_by_perl: v5.36.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
